# Generated by Django 5.0.1 on 2025-05-04 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_department_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='role',
        ),
    ]
