#version: "3.9"

services:

  ##########################
  # Database Services
  ##########################
#  mysql:
#    image: mysql:8
#    environment:
#      MYSQL_ROOT_PASSWORD: rootpass
#      MYSQL_DATABASE: biz_auth_db
#      MYSQL_USER: biz_auth_user
#      MYSQL_PASSWORD: biz_auth_pass
#    ports:
#      - "4307:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql

  postgres_auth:
    image: postgres:15
    environment:
      POSTGRES_DB: biz_auth_db
      POSTGRES_USER: biz_auth_user
      POSTGRES_PASSWORD: biz_auth_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  postgres_ops:
    image: postgres:15
    environment:
      POSTGRES_DB: biz_ops_db
      POSTGRES_USER: biz_ops_user
      POSTGRES_PASSWORD: biz_ops_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_ops_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "15672:15672"

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "22181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  ##########################
  # Microservices
  ##########################
  biz_auth:
    build: ./biz_auth
    depends_on:
      - postgres_auth
    environment:
      - DB_HOST=postgres_auth
      - DB_NAME=biz_auth_db
      - DB_USER=biz_auth_user
      - DB_PASSWORD=biz_auth_pass
    ports:
      - "8001:8000"
    volumes:
      - ./biz_auth:/code
    command: ["sh", "/code/entrypoint.sh"]

  biz_ops:
    build: ./biz_ops
    depends_on:
      - postgres_ops
    environment:
      - DB_HOST=postgres_ops
      - DB_NAME=biz_ops_db
      - DB_USER=biz_ops_user
      - DB_PASSWORD=biz_ops_pass
    ports:
      - "8002:8000"
    volumes:
      - ./biz_ops:/app

  biz_analytics:
    build: ./biz_analytics
    depends_on:
      - elasticsearch
      - redis
    environment:
      - ELASTIC_HOST=elasticsearch
      - REDIS_HOST=redis
    ports:
      - "8003:8000"
    volumes:
      - ./biz_analytics:/app

  biz_crm:
    build: ./biz_crm
    depends_on:
      - rabbitmq
      - kafka
      - redis
    environment:
      - RABBITMQ_HOST=rabbitmq
      - KAFKA_HOST=kafka
      - REDIS_HOST=redis
    ports:
      - "8004:8000"
    volumes:
      - ./biz_crm:/app

volumes:
#  mysql_data:
  postgres_auth_data:
  postgres_ops_data:
  elastic_data:
