#version: '3.8'

services:
  biz_auth:
    build: ./biz_auth
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://biz_auth_user:biz_auth_pass@mysql:3306/biz_auth_db
  biz_ops:
    build: ./biz_ops
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://biz_ops_user:biz_ops_pass@postgres:5432/biz_ops_db
  biz_analytics:
    build: ./biz_analytics
    depends_on:
      - elasticsearch
      - redis
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis://redis:6379/0
  biz_crm:
    build: ./biz_crm
    depends_on:
      - rabbitmq
      - kafka
      - redis
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672//
      - KAFKA_BROKER=kafka:9092
      - REDIS_URL=redis://redis:6379/0
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: biz_auth_db
      MYSQL_USER: biz_auth_user
      MYSQL_PASSWORD: biz_auth_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "4307:3306"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: biz_ops_db
      POSTGRES_USER: biz_ops_user
      POSTGRES_PASSWORD: biz_ops_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  elasticsearch:
    image: elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
volumes:
  mysql_data:
  postgres_data:
  es_data:

