#version: "3.9"

services:

  ##########################
  # Database Services
  ##########################
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: biz_auth_db
      MYSQL_USER: biz_auth_user
      MYSQL_PASSWORD: biz_auth_pass
    ports:
      - "4307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: biz_ops_db
      POSTGRES_USER: biz_ops_user
      POSTGRES_PASSWORD: biz_ops_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"

  ##########################
  # Microservices
  ##########################
  biz_auth:
    build: ./biz_auth
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_NAME=biz_auth_db
      - DB_USER=biz_auth_user
      - DB_PASSWORD=biz_auth_pass
    ports:
      - "8001:8000"
    volumes:
      - ./biz_auth:/code
    command: ["sh", "/code/entrypoint.sh"]

  biz_ops:
    build: ./biz_ops
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=biz_ops_db
      - DB_USER=biz_ops_user
      - DB_PASSWORD=biz_ops_pass
    ports:
      - "8002:8000"
    volumes:
      - ./biz_ops:/app

  biz_analytics:
    build: ./biz_analytics
    depends_on:
      - elasticsearch
      - redis
    environment:
      - ELASTIC_HOST=elasticsearch
      - REDIS_HOST=redis
    ports:
      - "8003:8000"
    volumes:
      - ./biz_analytics:/app

  biz_crm:
    build: ./biz_crm
    depends_on:
      - rabbitmq
      - kafka
      - redis
    environment:
      - RABBITMQ_HOST=rabbitmq
      - KAFKA_HOST=kafka
      - REDIS_HOST=redis
    ports:
      - "8004:8000"
    volumes:
      - ./biz_crm:/app

volumes:
  mysql_data:
  postgres_data:
  elastic_data:
