# Generated by Django 5.1.1 on 2025-05-28 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='melicode',
        ),
    ]
